

#creating image invoves these... Dockerfile->DockerCLient->DockerImage
#to create the docker file and give to docker client "$docker build ."



#Note: once u build image by $docker build .
# get image id by $docker images //this lists the images


#Below is how u create a docker file to generate an Imaage for ur application

#step1 (get a base image -- alpine is a os .. so we define which os we need)
FROM alpine 

#step2 (install a software-(binutils))
RUN apk add binutils
#step2.5
#step3





