# To simplify your Dockerfile and just use the official Node.js image, 
# you don't need to manually install nodejs and npm using apt because the official Node.js 
# image (like node:19.6-bullseye-slim) already comes with Node.js and npm pre-installed.
# So, you can combine everything into a single FROM directive and avoid the unnecessary apt update/install step.
# Pin specific version for stability
# Use slim for reduced image size 
FROM node:19.6-bullseye-slim 

# Specify working directory other than /
WORKDIR /usr/src/app 

# Copy only files required to install
# dependencies (better layer caching)
COPY ./api-node/package*.json .

RUN npm install

# Copy remaining source code AFTER installing dependencies. 
# Again, copy only the necessary files
COPY ./api-node/src .

CMD ["node", "index.js"]
