# Pin specific version for stability
FROM golang:1.19-bullseye 

WORKDIR /app

# Copy only files required to install dependencies (better layer caching)
COPY "./api-golang/go.mod" "./api-golang/go.sum" ./

RUN go mod download

COPY ./api-golang .

# Compile application during build rather than at runtime
RUN go build -o api-golang

CMD ["./api-golang"] 